### ISSUE TITLE
Create an Issue template 

### ISSUE THREAD

**Issue by felixfaisal** [felixfaisal/attack-on-web#26]
Create an issue template for segregation of issues

**Comment by 96RadhikaJadhav** [comment]
@felixfaisal Can I work on it?

**Comment by felixfaisal** [comment]
@96RadhikaJadhav sure, make sure you fork the repo and work on it. Also same for #3

**Comment by dev2919** [comment]
> @felixfaisal Can I work on it?

@96RadhikaJadhav You can refer the contribution guidelines here 
https://github.com/felixfaisal/attack-on-web/blob/main/CONTRIBUTING.md
