### ISSUE TITLE
GitHub Action for linting of code 

### ISSUE THREAD

**Issue by felixfaisal** [felixfaisal/attack-on-web#27]
Create a GitHub action for checking linting of code

**Comment by prashi23** [comment]
Hey @felixfaisal . @codingbug671 and I would like to work on this issue.

**Comment by felixfaisal** [comment]
@prashi23 Awesome, Do let us know if you need help with anything :)

**Comment by codingbug671** [comment]
hey @felixfaisal ! can you please assign me this issue as well :)
